### ISSUE TITLE
GetMatchHistoryBySequenceNum not work

### ISSUE THREAD

**Issue by John-Chan** [ribasco/async-gamequery-lib#20] opened 2017-11-03 05:30 UTC
because startSeqNum is used to pass match sequence number which is a 64 bit integer,but the constructor of GetMatchHistoryBySequenceNum only accept int32.

**Comment by ribasco** [comment] 2017-11-14 12:43
Duplicate of #14.

**Comment by ribasco** [comment] 2022-05-04 00:32
Reference b612971c2abe1ab83bae7d7c9fa8460f09b4e888

**Closed by ribasco** 2022-05-04 00:32 UTC
Labels: defect, dota 2, web-api
